### ISSUE TITLE
Grab the mouse

### ISSUE THREAD

**Issue by Eragonfr** [mrDIMAS/rusty-shooter#2]
I'm on Linux, with i3 on X11 or sway on wayland and i have a problem.
The mouse cursor is shown and the game does not grab it. So i'm not able to turn the player head because the mouse quit the window.
Is rg3d allowing that ? Grabbing the mouse, hide the cursor, and move it to keep it at center of the window ?

**Comment by mrDIMAS** [comment]
Sure, it can be done by using `set_cursor_pos` and `set_cursor` on window. I'll fix it in next commit.
