### ISSUE TITLE
[cargo] Import dependencies from git instead of local path

### ISSUE THREAD

**Issue by southerntofu** [mrDIMAS/rusty-shooter#4]
I just built rusty-shooter on my machine. I think the setup could be simpler if the `Cargo.toml` file referenced a `git` repository (in addition to the `version` from crates.io) for dependencies instead of a `path`.

If all rg3d crates did this, we could just:

```
git clone https://github.com/mrDIMAS/rusty-shooter
cd rusty-shooter
cargo run --release
```

See cargo docs about [multiple locations](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations) for a crate.

**Comment by mrDIMAS** [comment]
I'm afraid this won't work for development - I'm changing other rg3d-x libraries at the same time while I'm writing engine or game. The docs clearly tells that you can't have `path` and `git` at the same time. Correct me if I'm wrong.

**Comment by Eragonfr** [comment]
We can add a simple shell/bat file for the of setup all repository, or using the git native function of subrepository ?
That can make it more simple to use

**Comment by mcuelenaere** [comment]
You could setup a workspace and [override the dependencies](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html), eg like done at https://github.com/rust-lang/cargo/issues/6126

**Comment by mrDIMAS** [comment]
Closing this because I added workspace for rg3d and now there is no need to manually download 4 deps, just rg3d is enough.
