### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by jepotter1-archive** [mrDIMAS/rusty-shooter#6]
The game averages at around 35-40 FPS. My computer should be able to handle a game like this at 60 FPS at least (it can do Xonotic and CS:GO at 200 FPS).

Specs:

- Radeon RX 570
- Ryzen 7 2700X
- 16 GB RAM (DDR4-3200)

I don't know anything about game development, but it would be interesting to see what kinds of optimizations can improve performance.

**Comment by mrDIMAS** [comment]
Hi, there is an issue with shadows from point lights, they're eating tons of GPU resources. As a fix you could reduce "Point shadows distance" in Options->Graphics. Performance of the renderer should be improved and it is somewhere on my TODO list.

**Comment by jepotter1-archive** [comment]
Hmm... It seems like there's still a bit of visual artifacting and stuttering once in a while even when I turn off all the shadows, especially when there are lots of things moving in view.

**Comment by mrDIMAS** [comment]
May I ask you to make a video (or maybe screenshots with artifacts)? 

I played a bit an there are noticeable one-frame delay when new bot spawning - its model for a frame is so huge so it fills all the level, this looks like visual artifacting. But maybe you have other issues?

Also, recently I added "Use Light Scatter" option in the graphics settings, disabling it can improve performance.

**Comment by mrDIMAS** [comment]
I'm closing this issue since I did significant performance improvements in rg3d recently.
